Fix spurious exception at end of input.
When triggering end a second time, some structures have sometimes already
been cleaned up, leading to exceptions. Furthermore there is no need to
effectively end the stream twice.

The full exception was:
  _stream_readable.js:594
        state.pipes.forEach(write);
                    ^
  TypeError: Cannot call method 'forEach' of null
      at flow (_stream_readable.js:594:19)
      at Socket.<anonymous> (_stream_readable.js:573:7)
      at Socket.EventEmitter.emit (events.js:92:17)
      at onwriteDrain (_stream_writable.js:283:12)
      at afterWrite (_stream_writable.js:271:5)
      at onwrite (_stream_writable.js:264:7)
      at Socket.WritableState.onwrite (_stream_writable.js:97:5)
      at Object.afterWrite (net.js:728:12)